<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Clavus.Hosting\Clavus.Hosting.csproj" />
        <ProjectReference Include="..\..\src\Clavus.Hosting.Web\Clavus.Hosting.Web.csproj" />
        <ProjectReference Include="..\..\src\Clavus.Configuration.Json\Clavus.Configuration.Json.csproj" />
        <ProjectReference Include="..\..\src\Clavus.Configuration.Yaml\Clavus.Configuration.Yaml.csproj" />
        <ClavusHost
            Include="HostApplication"
            HostBuilderType="Microsoft.Extensions.Hosting.HostApplicationBuilder"
            HostBuilderName="builder"
            HostType="Microsoft.Extensions.Hosting.IHost"
        />
    </ItemGroup>
</Project>
