<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
    <Import Project="$(MSBuildThisFileDirectory)../src/Clavus.Abstractions/build/Rocket.Surgery.Clavus.Abstractions.props" />
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <MergeCoverage>true</MergeCoverage>
        <IncludeTestAssembly>true</IncludeTestAssembly>
    </PropertyGroup>
</Project>
