//HintName: Clavus.Analyzers/Clavus.ClavusAttributesGenerator/Microsoft.CodeAnalysis.EmbeddedAttribute.cs
// <auto-generated/>
namespace Microsoft.CodeAnalysis
{
    internal sealed partial class EmbeddedAttribute : global::System.Attribute
    {
    }
}
