codecov:
  require_ci_to_pass: no
  bot: rsg-bot
  strict_yaml_branch: master

coverage:
  round: down
  precision: 2

  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%
    changes: no

comment:
  branch: master
