trigger:
  branches:
    include:
      - master
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.9.2
      endpoint: github

variables:
  - group: rsg-bot
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: '61159895-7ba0-464b-b0ab-558625c0830d'

jobs:
  - template: pipeline/nuke.yml@rsg
    parameters:
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      GitHub: true
      GitHubPackages: false
      DotNet21Version: "2.1.x"
      DotNetVersion: "2.2.x"
      DotNet3Version: "3.0.100-rc1-014190"
      NuGetVersion: "5.2.0"
