<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../../src/Clavus.Abstractions/build/Rocket.Surgery.Clavus.Abstractions.props" />
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
        <ImportConventions>true</ImportConventions>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Testing.Extensions.CrashDump" />
        <PackageReference Include="Microsoft.Testing.Extensions.HangDump" />
        <PackageReference Include="TUnit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Clavus\Rocket.Surgery.Clavus.csproj" />
        <ProjectReference Include="..\Sample.Core\Sample.Core.csproj" />
    </ItemGroup>

    <Import Project="../../src/Clavus.Abstractions/build/Rocket.Surgery.Clavus.Abstractions.targets" />
</Project>
