<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Microsoft.Playwright" />
        <PackageReference Include="Verify.AngleSharp" />
        <PackageReference Include="Verify.Playwright" />
        <ProjectReference Include="..\..\sample\Sample.BlazorWasm\Sample.BlazorWasm.csproj" />
        <ProjectReference Include="..\..\src\Clavus.Hosting.WebAssembly\Clavus.Hosting.WebAssembly.csproj" />
        <ProjectReference Include="..\..\src\Clavus.Configuration.Json\Clavus.Configuration.Json.csproj" />
        <ProjectReference Include="..\..\src\Clavus.Configuration.Yaml\Clavus.Configuration.Yaml.csproj" />
        <PackageReference Include="bunit.web" />
    </ItemGroup>
</Project>
