<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <PackageDescription>Provides Autofac support for a Rocket Surgery Application</PackageDescription>
        <PackageTags>$(PackageTags);autofac</PackageTags>
    </PropertyGroup>
    <ItemGroup>
        <ClavusPart Include="Autofac"
            Namespace="Clavus"
            ProvideServices="true"
            ParameterType="Autofac.ContainerBuilder"
            ParameterName="builder" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Clavus\Clavus.csproj" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" />
        <InternalsVisibleTo Include="Rocket.Surgery.Extensions.Autofac.Tests" />
    </ItemGroup>
</Project>
