<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\src\Clavus.Abstractions\Rocket.Surgery.Clavus.Abstractions.csproj" />
        <ProjectReference
            Include="..\..\src\Clavus.Analyzers\Rocket.Surgery.Clavus.Analyzers.csproj"
            IncludeAssets="all"
            OutputItemType="Analyzer"
            ReferenceOutputAssembly="false"
        />
    </ItemGroup>

    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
    </PropertyGroup>
</Project>
