<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\src\Clavus\Clavus.csproj" />
        <ProjectReference
            Include="..\..\src\Clavus.Analyzers\Clavus.Analyzers.csproj"
            IncludeAssets="all"
            OutputItemType="Analyzer"
            ReferenceOutputAssembly="false"
        />
        <ClavusPart Include="DatabaseConfigurator" Namespace="Clavus" ParameterType="Sample.Core.Databases.IDatabaseConfigurator" ParameterName="builder" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
</Project>
