<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-browser</TargetFrameworks>
        <PackageDescription>
            Adds helpers to easily bootstrap an application using conventions by just using the correct extension method. This adds command line
            operations, additional configuration, logging and service injections by convention.
        </PackageDescription>
        <PackageTags>$(PackageTags);hosting;generic host</PackageTags>
    </PropertyGroup>
    <ItemGroup>
        <ClavusPart
            Include="WebAssemblyHostBuilder"
            ParameterType="global::Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder"
            ParameterName="builder"
        />
        <ClavusPart
            Include="WebAssemblyHost"
            ParameterType="global::Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost"
            ParameterName="host"
        />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Clavus\Clavus.csproj" />
        <InternalsVisibleTo Include="Clavus.WebAssembly.Hosting.Tests" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    </ItemGroup>
    <ItemGroup />
</Project>
