using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace Clavus;

/// <summary>
/// This class is used by the source generator to allow the conventions provided to be overridden by the caller.
/// </summary>
/// <remarks>
/// This is to allow for returning different conventions that are generated by something like a helper assembly,
/// or even a unit test assembly.
///
/// The concept really means that a given host can have it's production conventions and allow test assemblies
/// to override them.  Then the test assemblies can provide mocks and stubs just for testing.
/// </remarks>
[PublicAPI]
[EditorBrowsable(EditorBrowsableState.Never)]
public static class ImportHelpers
{
    /// <summary>
    /// The external conventions that have been provided by the caller.
    /// </summary>
    /// <remarks>
    /// If the `IsTestProject` property is detected, the generator will inject a <see cref="ModuleInitializerAttribute"/> the automatically assigns the external conventions.
    /// </remarks>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static Func<ClavusContextBuilder>? Tectum { get; set; }
}
