<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\sample\AspireSample\AspireSample.csproj" />
        <ProjectReference Include="..\..\src\Clavus.Aspire\Rocket.Surgery.Clavus.Aspire.csproj" />
        <ProjectReference Include="..\..\src\Clavus.Aspire.Testing\Rocket.Surgery.Clavus.Aspire.Testing.csproj" />
    </ItemGroup>
</Project>
