<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Clavus.Hosting\Rocket.Surgery.Clavus.Hosting.csproj" />
        <ProjectReference Include="..\..\src\Clavus.Configuration.Json\Rocket.Surgery.Clavus.Configuration.Json.csproj" />
        <ProjectReference Include="..\..\src\Clavus.Configuration.Yaml\Rocket.Surgery.Clavus.Configuration.Yaml.csproj" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    </ItemGroup>
</Project>
