<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <PackageDescription>Provides Serilog support for a Rocket Surgery Application</PackageDescription>
        <PackageTags>$(PackageTags);Serilog</PackageTags>
    </PropertyGroup>
    <ItemGroup>
        <ClavusPart Include="Serilog" Namespace="Clavus" ParameterType="global::Serilog.LoggerConfiguration" ParameterName="loggerConfiguration" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <ProjectReference Include="..\Clavus\Clavus.csproj" />

      <ProjectReference
        Include="..\Clavus.Analyzers\Clavus.Analyzers.csproj"
        IncludeAssets="analyzers;build;buildMultitargeting;buildTransitive"
        ExcludeAssets="compile;runtime;native"
        PrivateAssets="contentfiles;build;buildMultitargeting;buildTransitive"
        OutputItemType="Analyzer"
        ReferenceOutputAssembly="false"
      />
    </ItemGroup>
</Project>
