<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchMarkDotNet" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Clavus.Hosting\Clavus.Hosting.csproj" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Clavus.Analyzers\Clavus.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ClavusHost
            Include="HostApplication"
            Namespace="Clavus.Hosting"
            HostBuilderType="Microsoft.Extensions.Hosting.HostApplicationBuilder"
            HostBuilderName="builder"
            HostType="Microsoft.Extensions.Hosting.IHost"
        />
    </ItemGroup>
</Project>
