<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\src\Clavus.CommandLine\Rocket.Surgery.Clavus.CommandLine.csproj" />
        <ProjectReference Include="..\..\src\Clavus.Hosting\Rocket.Surgery.Clavus.Hosting.csproj" />
        <ProjectReference
            Include="..\..\src\Clavus.Analyzers\Rocket.Surgery.Clavus.Analyzers.csproj"
            IncludeAssets="all"
            OutputItemType="Analyzer"
            ReferenceOutputAssembly="false"
        />
        <ProjectReference Include="..\Sample.Core\Sample.Core.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
</Project>
