<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <ProjectReference Include="..\..\src\Clavus.OpenTelemetry\Clavus.OpenTelemetry.csproj" />
        <ProjectReference Include="..\..\src\Clavus\Clavus.csproj" />
        <ProjectReference Include="..\..\src\Clavus.Hosting\Clavus.Hosting.csproj" />

        <PackageReference Include="OpenTelemetry.Exporter.InMemory" />

        <ClavusHost
            Include="HostApplication"
            HostBuilderType="global::Microsoft.Extensions.Hosting.HostApplicationBuilder"
            HostBuilderName="builder"
            HostType="global::Microsoft.Extensions.Hosting.IHost"
            HelperName="global::Clavus.ClavusHostApplicationHelpers"
        />
    </ItemGroup>
</Project>