<Project>

  <PropertyGroup>
    <ClavusEnableJsonConfiguration Condition="'$(ClavusEnableJsonConfiguration)' == ''">false</ClavusEnableJsonConfiguration>
    <ClavusEnableYamlConfiguration Condition="'$(ClavusEnableYamlConfiguration)' == ''">true</ClavusEnableYamlConfiguration>
    <ClavusEnableTomlConfiguration Condition="'$(ClavusEnableTomlConfiguration)' == ''">false</ClavusEnableTomlConfiguration>
    <ClavusEnableAutofac Condition="'$(ClavusEnableAutofac)' == ''">false</ClavusEnableAutofac>
    <ClavusEnableDryIoc Condition="'$(ClavusEnableDryIoc)' == ''">false</ClavusEnableDryIoc>
    <ClavusEnableSerilog Condition="'$(ClavusEnableSerilog)' == ''">false</ClavusEnableSerilog>
  </PropertyGroup>

</Project>
