using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace Clavus.Support.Configuration;

/// <summary>
///     The generated output for a single discovered <see cref="ConfigurationFileGroup" />: the strongly-typed
///     configuration class (design.md Decision 4) and its paired <see cref="Clavus.IConfigurationPart" />
///     implementation (design.md Decision 4 / tasks.md 4.2).
/// </summary>
internal sealed record GeneratedConfigurationOutput(
    string HintName,
    string SourceText,
    string RootNamespace,
    string PartTypeName);

/// <summary>
///     Emits the generated configuration class shape (nested objects -&gt; nested generated classes, task 3.2)
///     and the paired part implementation (task 4.2) for a single <see cref="ConfigurationFileGroup" />, into the
///     owning library's root namespace.
/// </summary>
/// <remarks>
///     <b>Decision (deviation from design.md's literal text):</b> design.md/tasks.md (4.1) call for a new
///     <c>IConfigurationPart</c> interface "alongside <c>IClavusPart</c>". That name is already taken: this
///     repository has an unrelated, pre-existing generic "ClavusPart" MSBuild-item templating mechanism
///     (<c>Clavus.Parts.targets</c>, driven by <c>&lt;ClavusPart Include="Configuration" /&gt;</c> /
///     <c>&lt;ClavusPart Include="Service" ... /&gt;</c> in <c>Clavus.csproj</c>) that already generates
///     <c>Clavus.IConfigurationPart.Register(IClavusContext, IConfigurationBuilder)</c> and
///     <c>Clavus.IServicePart.Register(IClavusContext, IServiceCollection)</c>. Rather than introduce a
///     colliding/duplicate type, each generated part class here implements <i>both</i> pre-existing interfaces
///     directly - one <c>Register</c> overload adds the configuration source, the other binds the generated
///     class via <c>AddOptions&lt;T&gt;().Bind(...)</c>. This still satisfies "always included in the export set
///     without a [ClavusExport] attribute" (task 4.3), since export inclusion is driven by this generator knowing
///     the type name directly, not by which interface it implements.
///     <br />
///     Naming for nested object/array-of-object shapes reuses the owning property's PascalCase name as the
///     nested class name (e.g. a <c>"logging"</c> property becomes a nested <c>Logging</c> class). This is a
///     first-pass convention; design.md leaves "generated-type naming for multiple config files/nested shapes" as
///     an open question (see openspec/changes/clavus-managed-configuration/design.md, Open Questions).
/// </remarks>
internal static class ConfigurationClassEmitter
{
    public static GeneratedConfigurationOutput Emit(
        ConfigurationFileGroup group,
        string rootNamespace,
        bool useNodaTime
    )
    {
        var rootClassName = ConfigurationIdentifiers.ToRootClassName(group.BaseName);
        var partTypeName = $"{rootClassName}Part";
        var rootNode = ConfigurationNode.Build(group.FlatValues);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.Append("namespace ").Append(rootNamespace).AppendLine(";");
        sb.AppendLine();
        AppendGeneratedAttribute(sb, 0);
        sb.Append("public sealed partial class ").AppendLine(rootClassName);
        sb.AppendLine("{");
        AppendClassBody(sb, rootNode, useNodaTime, 1);
        sb.AppendLine("}");
        sb.AppendLine();

        AppendGeneratedAttribute(sb, 0);
        sb.Append("public sealed class ").Append(partTypeName).AppendLine(" : global::Clavus.IConfigurationPart, global::Clavus.IServicePart");
        sb.AppendLine("{");
        sb.AppendLine("    // Adds this file's configuration source (Clavus's pre-existing \"Configuration\" part stage).");
        sb.Append("    public void Register(global::Clavus.IClavusContext context, global::Microsoft.Extensions.Configuration.IConfigurationBuilder builder)");
        sb.AppendLine();
        sb.AppendLine("    {");
        sb.Append("        builder.").Append(AddFileMethodName(group.Format)).Append('(')
          .Append(SymbolDisplay.FormatLiteral(group.RelativePath, true)).AppendLine(", optional: true, reloadOnChange: true);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // Binds the generated configuration class (Clavus's pre-existing \"Service\" part stage).");
        sb.Append("    public void Register(global::Clavus.IClavusContext context, global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine();
        sb.AppendLine("    {");
        sb.Append("        services.AddOptions<").Append(rootClassName).AppendLine(">().Bind(context.Configuration);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return new(
            $"{rootClassName}.g.cs",
            sb.ToString(),
            rootNamespace,
            $"global::{rootNamespace}.{partTypeName}"
        );
    }

    private static void AppendClassBody(StringBuilder sb, ConfigurationNode node, bool useNodaTime, int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);
        foreach (var pair in node.Children.OrderBy(static kvp => kvp.Key, StringComparer.Ordinal))
        {
            var propertyName = ConfigurationIdentifiers.ToPascalCase(pair.Key);
            var child = pair.Value;

            if (child.IsLeaf)
            {
                var kind = ConfigurationValueTypeInference.Infer(child.LeafValue);
                var clrType = ConfigurationValueTypeInference.ToClrTypeName(kind, useNodaTime);
                sb.Append(indent).Append("public ").Append(clrType).Append("? ").Append(propertyName).AppendLine(" { get; set; }");
                continue;
            }

            if (child.IsArray)
            {
                var representative = child.Children.Values.FirstOrDefault();
                if (representative is null or { IsLeaf: true, })
                {
                    var kind = ConfigurationValueTypeInference.Infer(representative?.LeafValue);
                    var clrType = ConfigurationValueTypeInference.ToClrTypeName(kind, useNodaTime);
                    sb.Append(indent).Append("public global::System.Collections.Generic.List<").Append(clrType).Append(">? ").Append(propertyName)
                      .AppendLine(" { get; set; }");
                }
                else
                {
                    var nestedClassName = propertyName;
                    AppendGeneratedAttribute(sb, indentLevel);
                    sb.Append(indent).Append("public sealed partial class ").AppendLine(nestedClassName);
                    sb.Append(indent).AppendLine("{");
                    AppendClassBody(sb, representative, useNodaTime, indentLevel + 1);
                    sb.Append(indent).AppendLine("}");
                    sb.Append(indent).Append("public global::System.Collections.Generic.List<").Append(nestedClassName).Append(">? ").Append(propertyName)
                      .AppendLine(" { get; set; }");
                }

                continue;
            }

            // Nested object -> nested generated class (design.md Decision 4 / task 3.2).
            var nestedName = propertyName;
            AppendGeneratedAttribute(sb, indentLevel);
            sb.Append(indent).Append("public sealed partial class ").AppendLine(nestedName);
            sb.Append(indent).AppendLine("{");
            AppendClassBody(sb, child, useNodaTime, indentLevel + 1);
            sb.Append(indent).AppendLine("}");
            sb.Append(indent).Append("public ").Append(nestedName).Append("? ").Append(propertyName).AppendLine(" { get; set; }");
        }
    }

    private static void AppendGeneratedAttribute(StringBuilder sb, int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);
        sb.Append(indent).AppendLine("[GeneratedCode(\"Clavus.Analyzers\", null)]");
    }

    private static string AddFileMethodName(ConfigurationFileFormat format) =>
        format switch
        {
            ConfigurationFileFormat.Json => "AddJsonFile",
            ConfigurationFileFormat.Yaml => "AddYamlFile",
            ConfigurationFileFormat.Toml => "AddTomlFile",
            _ => "AddJsonFile",
        };
}
