using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace Clavus.Support.Configuration;

/// <summary>
///     Emits <c>[assembly: Clavus.ConfigurationAssembly("&lt;name&gt;", "&lt;relativePath&gt;")]</c> for each
///     discovered <see cref="ConfigurationFileGroup" /> in the current project (task 2.6). This is
///     format-agnostic - every discovered group is marked, regardless of whether the generator was also able to
///     emit a strongly-typed class for it (JSON only, for now - see <see cref="ConfigurationClassEmitter" />),
///     since the marker's purpose is packaging/manifest visibility, not codegen.
/// </summary>
internal static class ConfigurationAssemblyMarkerEmitter
{
    public const string HintName = "ClavusConfigurationAssembly.g.cs";

    public static string Emit(ImmutableArray<ConfigurationFileGroup> groups)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        foreach (var group in groups.OrderBy(static g => g.BaseName, StringComparer.Ordinal))
        {
            sb.Append("[assembly: global::Clavus.ConfigurationAssembly(")
              .Append(SymbolDisplay.FormatLiteral(group.BaseName, true))
              .Append(", ")
              .Append(SymbolDisplay.FormatLiteral(group.RelativePath, true))
              .AppendLine(")]");
        }

        return sb.ToString();
    }
}
