using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Clavus.Support.Configuration;

/// <summary>
///     Host-side generator pass (task 2.7): reads <c>[assembly: Clavus.ConfigurationAssembly(...)]</c> markers off
///     every referenced assembly (reusing <see cref="MsBuildExtensions" />'s reference-walk mechanism, the same
///     one used to discover <c>[ClavusExport]</c> conventions transitively - design.md Decision 2), plus this
///     project's own discovered groups, and emits a host-visible <c>ClavusConfigurationManifest</c> type listing
///     every contributing assembly and its relative configuration path.
/// </summary>
internal static class ConfigurationManifestEmitter
{
    public const string HintName = "ClavusConfigurationManifest.g.cs";

    public static string Emit(
        Compilation compilation,
        string rootNamespace,
        ImmutableArray<ConfigurationFileGroup> ownGroups,
        string ownAssemblyName
    )
    {
        var entries = ownGroups
                     .Select(g => (AssemblyName: ownAssemblyName, Name: g.BaseName, g.RelativePath))
                     .Concat(compilation.GetClavusConfigurationReferences().Select(z => (z.AssemblyName, z.Name, z.RelativePath)))
                     .OrderBy(z => z.AssemblyName, StringComparer.Ordinal)
                     .ThenBy(z => z.Name, StringComparer.Ordinal)
                     .ToImmutableArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (rootNamespace is { Length: > 0, })
        {
            sb.Append("namespace ").Append(rootNamespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine("///     The set of assemblies (this one, and any referenced) contributing a managed Clavus");
        sb.AppendLine("///     configuration file, and the relative path each was packaged/copied to.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[System.CodeDom.Compiler.GeneratedCode(\"Clavus.Analyzers\", null)]");
        sb.AppendLine("internal static class ClavusConfigurationManifest");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Contributing assembly name, configuration base name, and relative path.</summary>");
        sb.AppendLine(
            "    public static global::System.Collections.Generic.IReadOnlyList<(string AssemblyName, string Name, string RelativePath)> Entries { get; } = "
        );
        if (entries.Length == 0)
        {
            sb.AppendLine("        global::System.Array.Empty<(string, string, string)>();");
        }
        else
        {
            sb.AppendLine("        new (string AssemblyName, string Name, string RelativePath)[]");
            sb.AppendLine("        {");
            foreach (var (AssemblyName, Name, RelativePath) in entries)
            {
                sb.Append("            (")
                  .Append(SymbolDisplay.FormatLiteral(AssemblyName, true))
                  .Append(", ")
                  .Append(SymbolDisplay.FormatLiteral(Name, true))
                  .Append(", ")
                  .Append(SymbolDisplay.FormatLiteral(RelativePath, true))
                  .AppendLine("),");
            }

            sb.AppendLine("        };");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}
