<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
    <Import Project="$(MSBuildThisFileDirectory)../src/Clavus/build/Clavus.props" />
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <NoWarn>$(NoWarn);CA1050</NoWarn>
        <ImportClavusAssembly>true</ImportClavusAssembly>
    </PropertyGroup>
</Project>
