name: Publish Nuget

on:
  release:
    types:
      - released
  workflow_run:
    workflows: ['ci']
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - name: Download artifact
        if: github.event_name != 'release'
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml
          run_id: ${{ github.event.id }}
          name: nuget

      # - uses: actions/download-artifact@v2
      #   with:
      #     name: nuget

      - name: nuget.org
        # continue-on-error: true
        if: github.event_name == 'release'
        env:
          ApiKey: ${{ secrets.RSG_NUGET_API_KEY }}
        shell: pwsh
        run: |
          dotnet nuget push **/*.nupkg --skip-duplicate --api-key $ENV:ApiKey --source nuget.org

      - name: dev.azure.com
        # continue-on-error: true
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        env:
          ApiKey: ${{ secrets.RSG_AZURE_DEVOPS }}
        shell: pwsh
        run: |
          dotnet nuget add source https://rocketsurgeonsguild.pkgs.visualstudio.com/Libraries/_packaging/Packages/nuget/v3/index.json --store-password-in-clear-text --name LibrariesPackages --username azuredevops --password $ENV:ApiKey
          dotnet nuget push **/*.nupkg --skip-duplicate --api-key azuredevops --source LibrariesPackages

      - name: preview.dev.azure.com
        # continue-on-error: true
        if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main'
        env:
          ApiKey: ${{ secrets.RSG_AZURE_DEVOPS }}
        shell: pwsh
        run: |
          dotnet nuget add source https://rocketsurgeonsguild.pkgs.visualstudio.com/Libraries/_packaging/Preview/nuget/v3/index.json --store-password-in-clear-text --name LibrariesPreview --username azuredevops --password $ENV:ApiKey
          dotnet nuget push **/*.nupkg --skip-duplicate --api-key azuredevops --source LibrariesPreview
